AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/**/*"
    - "config/routes.rb"
  TargetRubyVersion: 3.1.1
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
